# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Vaani-Desktop-AI-master\TARSGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TARSUI(object):
    def setupUi(self, TARSUI):
        TARSUI.setObjectName("TARSUI")
        TARSUI.resize(1358, 830)
        self.centralwidget = QtWidgets.QWidget(TARSUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-110, -10, 1481, 841))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(
            "E:\TARS AI\Intro-HELLO-FUTURE-1920x1080_v2.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 740, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(15, 235, 255);\n"
                                      "background-color: rgb(170, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 740, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(17, 144, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        TARSUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(TARSUI)
        QtCore.QMetaObject.connectSlotsByName(TARSUI)

    def retranslateUi(self, TARSUI):
        _translate = QtCore.QCoreApplication.translate
        TARSUI.setWindowTitle(_translate("TARSUI", "MainWindow"))
        self.pushButton.setText(_translate("TARSUI", "RUN"))
        self.pushButton_2.setText(_translate("TARSUI", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TARSUI = QtWidgets.QMainWindow()
    ui = Ui_TARSUI()
    ui.setupUi(TARSUI)
    TARSUI.show()
    sys.exit(app.exec_())
